import ring from "../assets/ring1.png";
import earring1 from "../assets/ring1.png";
import earring2 from "../assets/ring2.png";
import earring3 from "../assets/ring3.png";

export const CATEGORY_FILTERS = [
  { id: 1, label: "Earrings" },
  { id: 2, label: "Bracelet" },
  { id: 3, label: "Bangles" },
  { id: 4, label: "Ring" },
  { id: 5, label: "Pendant" },
  { id: 6, label: "Anklet" },
  { id: 7, label: "Necklace" },
  { id: 8, label: "Chain" },
  { id: 9, label: "Nose Pin" },
  { id: 10, label: "Toe Ring" },
];

export const MATERIAL_FILTERS = [
  { id: 1, label: "Gold" },
  { id: 2, label: "Silver" },
  { id: 3, label: "Diamond" },
  { id: 4, label: "Platinum" },
];

export const OCCASION_FILTERS = [
  { id: 1, label: "Daily" },
  { id: 2, label: "Party" },
  { id: 3, label: "Wedding" },
  { id: 4, label: "Engagement" },
  { id: 5, label: "Festival" },
];


export const trending = [
  {
    id: 1,
    name: "Emerald Earrings",
    sku: "18040",
    price: 20000,
    oldPrice: 22000,
    image: ring,
    category: "Earrings",
    material: "Gold",
    occasion: "Party",
  },
  {
    id: 2,
    name: "Silver Bracelet",
    sku: "18039",
    price: 8000,
    oldPrice: 9500,
    image: earring2,
    category: "Bracelet",
    material: "Silver",
    occasion: "Daily",
  },
  {
    id: 3,
    name: "Diamond Stud Earrings",
    sku: "18041",
    price: 35000,
    oldPrice: 38000,
    image: earring2,
    category: "Earrings",
    material: "Diamond",
    occasion: "Wedding",
  },
  {
    id: 4,
    name: "Gold Bangles",
    sku: "18042",
    price: 45000,
    oldPrice: 50000,
    image: earring1,
    category: "Bangles",
    material: "Gold",
    occasion: "Wedding",
  },
  {
    id: 5,
    name: "Platinum Ring",
    sku: "18043",
    price: 55000,
    oldPrice: 60000,
    image: ring,
    category: "Ring",
    material: "Platinum",
    occasion: "Engagement",
  },
  {
    id: 6,
    name: "Gold Pendant",
    sku: "18044",
    price: 15000,
    oldPrice: 18000,
    image: earring3,
    category: "Pendant",
    material: "Gold",
    occasion: "Daily",
  },
  {
    id: 7,
    name: "Silver Anklet",
    sku: "18045",
    price: 6000,
    oldPrice: 7500,
    image: earring2,
    category: "Anklet",
    material: "Silver",
    occasion: "Daily",
  },
  {
    id: 8,
    name: "Diamond Necklace",
    sku: "18046",
    price: 120000,
    oldPrice: 130000,
    image: earring3,
    category: "Necklace",
    material: "Diamond",
    occasion: "Wedding",
  },
  {
    id: 9,
    name: "Gold Chain",
    sku: "18047",
    price: 30000,
    oldPrice: 34000,
    image: ring,
    category: "Chain",
    material: "Gold",
    occasion: "Daily",
  },
  {
    id: 10,
    name: "Rose Gold Bracelet",
    sku: "18048",
    price: 22000,
    oldPrice: 26000,
    image: earring1,
    category: "Bracelet",
    material: "Rose Gold",
    occasion: "Party",
  },
  {
    id: 11,
    name: "Navarathna Ring",
    sku: "18049",
    price: 40000,
    oldPrice: 45000,
    image: earring2,
    category: "Ring",
    material: "Gold",
    occasion: "Festival",
  },
  {
    id: 12,
    name: "Gold Nose Pin",
    sku: "18050",
    price: 5000,
    oldPrice: 6500,
    image: earring3,
    category: "Nose Pin",
    material: "Gold",
    occasion: "Daily",
  },
  {
    id: 13,
    name: "Diamond Couple Band",
    sku: "18051",
    price: 70000,
    oldPrice: 78000,
    image: ring,
    category: "Ring",
    material: "Diamond",
    occasion: "Engagement",
  },
  {
    id: 14,
    name: "Silver Toe Ring",
    sku: "18052",
    price: 3000,
    oldPrice: 4200,
    image: earring1,
    category: "Toe Ring",
    material: "Silver",
    occasion: "Daily",
  },
  {
    id: 15,
    name: "Gold Hoop Earrings",
    sku: "18053",
    price: 18000,
    oldPrice: 21000,
    image: earring2,
    category: "Earrings",
    material: "Gold",
    occasion: "Party",
  },
  {
    id: 16,
    name: "Platinum Necklace",
    sku: "18054",
    price: 95000,
    oldPrice: 105000,
    image: earring3,
    category: "Necklace",
    material: "Platinum",
    occasion: "Wedding",
  },
  {
    id: 17,
    name: "Gold Clip Bangle",
    sku: "18055",
    price: 26000,
    oldPrice: 29000,
    image: ring,
    category: "Bangles",
    material: "Gold",
    occasion: "Daily",
  },
  {
    id: 18,
    name: "Silver Pendant",
    sku: "18056",
    price: 7000,
    oldPrice: 9000,
    image: earring1,
    category: "Pendant",
    material: "Silver",
    occasion: "Daily",
  },
  {
    id: 19,
    name: "Diamond Drop Earrings",
    sku: "18057",
    price: 48000,
    oldPrice: 52000,
    image: earring2,
    category: "Earrings",
    material: "Diamond",
    occasion: "Party",
  },
  {
    id: 20,
    name: "Gold Mangalsutra",
    sku: "18058",
    price: 65000,
    oldPrice: 72000,
    image: earring3,
    category: "Necklace",
    material: "Gold",
    occasion: "Wedding",
  },
];
